spaces=' '* 25
print('%s 12 butts wynd' % spaces)
print('%s twinklebottom heath' % spaces)
print('%s west snoring' % spaces)
print()
print()
print("Dear Sir")
print()
print("I wish to report that titles are missing from the")
print("outside toilet roof.")
print("I think it was a bad wind the other night that blew them away.")
print()
print("regards")
print("malcom dithering")
